apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jaeger-badger-data
  namespace: monitoring

spec:
  accessModes:
    - ReadWriteOnce

  storageClassName: auto-ebs-gp3

  resources:
    requests:
      storage: 10Gi
