{
 "title": "External Reliability",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "External Probe",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{\r\n  job=\"online-boutique-external\"\r\n}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "External Availability — 30d",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\n  1 -\r\n  slo:sli_error:ratio_rate30d{\r\n    sloth_service=\"online-boutique-external\",\r\n    sloth_slo=\"availability\"\r\n  }\r\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Burn Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "slo:current_burn_rate:ratio{\r\n  sloth_service=\"online-boutique-external\",\r\n  sloth_slo=\"availability\"\r\n}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Budget Remaining",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "slo:period_error_budget_remaining:ratio{\r\n  sloth_service=\"online-boutique-external\",\r\n  sloth_slo=\"availability\"\r\n} * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Burn Rate ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "slo:sli_error:ratio_rate5m{\r\n  sloth_service=\"online-boutique-external\",\r\n  sloth_slo=\"availability\"\r\n}\r\n/\r\nscalar(\r\n  slo:error_budget:ratio{\r\n    sloth_service=\"online-boutique-external\",\r\n    sloth_slo=\"availability\"\r\n  }\r\n)",
     "legendFormat": "5m Burn Rate"
    },
    {
     "expr": "slo:sli_error:ratio_rate1h{\r\n  sloth_service=\"online-boutique-external\",\r\n  sloth_slo=\"availability\"\r\n}\r\n/\r\nscalar(\r\n  slo:error_budget:ratio{\r\n    sloth_service=\"online-boutique-external\",\r\n    sloth_slo=\"availability\"\r\n  }\r\n)",
     "legendFormat": "1h Burn Rate"
    }
   ]
  }
 ]
}