{
 "title": "Frontend SLO",
 "tags": [
  "slo",
  "frontend",
  "sloth"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Frontend SLO",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 -\r\nmax(\r\n  slo:sli_error:ratio_rate1d{\r\n    sloth_service=\"frontend\",\r\n    sloth_slo=\"availability\"\r\n  }\r\n)"
    }
   ]
  },
  {
   "title": "Error Budget Remaining",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 -\r\n(\r\n  max(\r\n    slo:sli_error:ratio_rate1d{\r\n      sloth_service=\"frontend\",\r\n      sloth_slo=\"availability\"\r\n    }\r\n  )\r\n  / 0.001\r\n)"
    }
   ]
  },
  {
   "title": "SLO Error Ratio - 5m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(\r\n  slo:sli_error:ratio_rate1d{\r\n    sloth_service=\"frontend\",\r\n    sloth_slo=\"availability\"\r\n  }\r\n)",
     "legendFormat": "5m error ratio"
    }
   ]
  },
  {
   "title": "Current Burn Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(\r\n  slo:sli_error:ratio_rate1d{\r\n    sloth_service=\"frontend\",\r\n    sloth_slo=\"availability\"\r\n  }\r\n) / 0.001",
     "legendFormat": "Burn rate"
    }
   ]
  }
 ]
}