apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: github-actions-pr-validation
  namespace: argocd
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - applications
      - appprojects
    verbs:
      - get
      - list
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: github-actions-pr-validation
  namespace: argocd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: github-actions-pr-validation
subjects:
  - kind: Group
    name: github-actions-pr-validation
    apiGroup: rbac.authorization.k8s.io
