apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: frontend-to-one-cartservice-delay
  namespace: chaos-mesh

spec:
  action: delay

  # Chaosを仕掛ける側
  mode: all
  selector:
    namespaces:
      - pr13
    labelSelectors:
      app: frontend

  # frontend → target の通信だけ
  direction: to

  # cartservice 2Podのうちランダムに1Pod
  target:
    mode: one
    selector:
      namespaces:
        - pr13
      labelSelectors:
        app: cartservice

  delay:
    latency: "1s"
    correlation: "100"
    jitter: "0ms"

  duration: "120s"
