apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: cartservice-pod-kill
  namespace: chaos-mesh
spec:
  action: pod-kill
  mode: one

  selector:
    namespaces:
      - pr13
    labelSelectors:
      app: cartservice
