apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blackbox-exporter
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: prometheus-blackbox-exporter
    targetRevision: 11.18.0

    helm:
      values: |
        config:
          modules:
            http_2xx:
              prober: http
              timeout: 5s
              http:
                method: GET
                preferred_ip_protocol: ip4
                follow_redirects: true

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
