apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-image-updater
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/argoproj/argo-helm.git
    chart: argocd-image-updater
    targetRevision: 2.0.0

    helm:
      releaseName: ImageUpdater

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
