apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istiod-1-30
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default

  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    chart: istiod
    targetRevision: 1.30.3
    helm:
      releaseName: istiod-1-30
      values: |
        revision: 1-30

  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
