apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jaeger
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://jaegertracing.github.io/helm-charts
    chart: jaeger
    targetRevision: 4.12.0

    helm:
      releaseName: jaeger

      values: |
        userconfig:
          service:
            extensions:
              - jaeger_storage
              - jaeger_query
              - healthcheckv2

            pipelines:
              traces:
                receivers:
                  - otlp
                processors:
                  - batch
                exporters:
                  - jaeger_storage_exporter

          extensions:
            healthcheckv2:
              use_v2: true
              http:
                endpoint: 0.0.0.0:13133

            jaeger_query:
              storage:
                traces: primary_store

            jaeger_storage:
              backends:
                primary_store:
                  badger:
                    ephemeral: false
                    directories:
                      keys: /badger/data/keys
                      values: /badger/data/values
                    ttl:
                      spans: 168h

          receivers:
            otlp:
              protocols:
                grpc:
                  endpoint: 0.0.0.0:4317
                http:
                  endpoint: 0.0.0.0:4318

          processors:
            batch: {}

          exporters:
            jaeger_storage_exporter:
              trace_storage: primary_store

        jaeger:
          extraVolumes:
            - name: badger-data
              persistentVolumeClaim:
                claimName: jaeger-badger-data

          extraVolumeMounts:
            - name: badger-data
              mountPath: /badger

          podSecurityContext:
            runAsNonRoot: true
            runAsUser: 10001
            runAsGroup: 10001
            fsGroup: 10001
            fsGroupChangePolicy: OnRootMismatch

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
