apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default

  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 77.5.0

    helm:
      releaseName: monitoring
      valuesObject:
        alertmanager:
          enabled: true

          alertmanagerSpec:
            secrets:
              - pagerduty-alertmanager
              - slack-alertmanager

          config:
            route:
              receiver: default
              routes:
                - matchers:
                    - sloth_severity="page"
                  receiver: sre-page

                - matchers:
                    - sloth_severity="ticket"
                  receiver: sre-ticket

            receivers:
              - name: default

              - name: sre-page
                pagerduty_configs:
                  - routing_key_file: /etc/alertmanager/secrets/pagerduty-alertmanager/routing-key
                    send_resolved: true

              - name: sre-ticket
                slack_configs:
                  - api_url_file: /etc/alertmanager/secrets/slack-alertmanager/webhook-url
                    channel: "#sre-ticket"
                    send_resolved: true
        grafana:
          enabled: true
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
        kube-state-metrics:
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
        prometheus:
          prometheusSpec:
            resources:
              requests:
                cpu: 500m
                memory: 1Gi
              limits:
                cpu: "1"
                memory: 2Gi
            additionalScrapeConfigs:
              - job_name: kubernetes-pods-istio
                kubernetes_sd_configs:
                  - role: pod

                relabel_configs:
                  - source_labels:
                      - __meta_kubernetes_pod_annotation_prometheus_io_scrape
                    action: keep
                    regex: "true"

                  - source_labels:
                      - __meta_kubernetes_pod_annotation_prometheus_io_path
                    action: replace
                    target_label: __metrics_path__
                    regex: "(.+)"

                  - source_labels:
                      - __address__
                      - __meta_kubernetes_pod_annotation_prometheus_io_port
                    action: replace
                    regex: "([^:]+)(?::\\d+)?;(\\d+)"
                    replacement: "$1:$2"
                    target_label: __address__

                  - source_labels:
                      - __meta_kubernetes_namespace
                    action: replace
                    target_label: namespace

                  - source_labels:
                      - __meta_kubernetes_pod_name
                    action: replace
                    target_label: pod

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

